version: 2

models:

    - name: sales
      description: "we are accessing the sales information"
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: "We want to make sure that the orders all have a corresponding id"
            tests : 
            - not_null 

          - name: products_id
            tests:
              - not_null

          - name: qty

          - name: turnover
            tests:
              - not_null

          - name: purchase_cost
            tests:
              - not_null
              
          - name: margin